Lab/web 1 2
Kre4/kre4.github.io pull request #1
Opened 2022-09-10 14:28 UTC by Kre4

2022-09-12 12:47 UTC, BakasaRus requested changes
Макет можно сделать красивее

2022-09-12 12:47 UTC, BakasaRus commented on lab1-2/index.html
> +            </div>
Используем [спойлеры](https://webref.ru/layout/pseudo-class-checked/spoiler)

2022-09-12 12:47 UTC, BakasaRus commented on lab1-2/index.html
> +    }
Какой-то неработающий код

2022-09-12 12:47 UTC, BakasaRus commented on lab1-2/index.html
> +        <h1 class="bordered-text additional-additional-text">Тут тоже</h1>
Несколько тегов `<h1/>` - не самая лучшая идея, лучше стилизовать `<h2/>`

2022-09-12 15:51 UTC, Kre4 commented on lab1-2/index.html
> +            </div>
заменил

2022-09-12 15:51 UTC, Kre4 commented on lab1-2/index.html
> +        <h1 class="bordered-text additional-additional-text">Тут тоже</h1>
добавил h1, h2, h3

2022-09-12 15:52 UTC, Kre4 commented on lab1-2/index.html
> +    }
теперь работающий (наверное)

2022-09-25 08:34 UTC, BakasaRus approved these changes
Макет бы ещё красивый, ну да ладно

2022-09-25 08:34 UTC, BakasaRus commented on lab1-2/index.html
> +            <h1 class="bordered-text gallery__header">Галерея известных пельменей</h1>
Второй `<h1/>` - не самое лучшее решение, сделай `<h2/>` (но это уже пойдёт во вторую лабу, видимо)

2022-10-03 10:49 UTC, BakasaRus requested changes
1. Добавить курсив через CSS
2. `letter-spacing`
3. `text-indent`
4. Зачёркивание и пр. через `text-decoration`

И посмотри про `mix-blend-mode`

2022-10-03 11:11 UTC, Kre4 commented
1. done
2. done
3. done
4. done
mix-blend-mode не касается меня, это вообще про смешение цветов на разных слоях, удалил его

2022-10-09 15:23 UTC, BakasaRus approved these changes

2022-10-09 15:23 UTC, BakasaRus commented on lab1-2/styles.css
> +    letter-spacing: normal; <!-- :) -->
Комментарии не так ставятся в CSS :)

2022-10-28 09:59 UTC, merged