Lab/web 4
Kre4/kre4.github.io pull request #3
Opened 2022-11-28 10:43 UTC by Kre4

2022-11-28 10:44 UTC, Kre4 commented
lab 4-5

2022-11-28 11:10 UTC, BakasaRus requested changes

2022-11-28 11:10 UTC, BakasaRus commented on lab1-2/scripts/nav-selector.js
> +    }
Вот тут **жизненно необходимо** поменять абзацы на нормальные ссылки и убрать этот кусок

2022-11-28 11:10 UTC, BakasaRus commented on lab1-2/scripts/nav-selector.js
> +    const navElement = document.getElementById(activePageId);
Вот тут лучше перебирать детей контейнера с навигацией и накидывать нужный класс, если совпали абсолютные ссылки

2022-11-28 11:10 UTC, BakasaRus commented on lab1-2/scripts/nav-selector.js
> +    element.style.borderColor = '#6a2cce';
Это лучше вынести в отдельный CSS-класс

2022-11-28 11:10 UTC, BakasaRus commented on lab1-2/scripts/time-load-component.js
> +});
1. Кажется, оно не совсем верно считает время. Попробуй слушать другое событие (https://learn.javascript.ru/onload-ondomcontentloaded)
2. Просят использовать IIFE

2022-11-28 11:10 UTC, BakasaRus commented on lab1-2/scripts/pelmeni-form-filter.js
> +        });
Это лучше вынести в HTML с помощью `<template/>`, потом брать в коде этот элемент и заполнять данными

2022-11-28 11:22 UTC, Kre4 commented on lab1-2/scripts/nav-selector.js
> +    }
поменял

2022-11-28 12:56 UTC, Kre4 commented on lab1-2/scripts/nav-selector.js
> +    element.style.borderColor = '#6a2cce';
вынес

2022-11-28 13:49 UTC, Kre4 commented on lab1-2/scripts/time-load-component.js
> +});
исправил

2022-11-28 14:01 UTC, Kre4 commented on lab1-2/scripts/pelmeni-form-filter.js
> +        });
вынес

2022-11-28 14:10 UTC, Kre4 commented on lab1-2/scripts/nav-selector.js
> +    const navElement = document.getElementById(activePageId);
сделал

2022-12-12 11:49 UTC, BakasaRus approved these changes

2022-12-13 08:13 UTC, merged